language: node_js
node_js:
- '0.12'
deploy:
  provider: heroku
  api_key:
    secure: IZDZzWrhcAMjVNmcJRfIu3aTa6yU4VlHaPjeZTt0oCKkPSlBATQ9Dh3dSNwyZp1WukPceYRrRJtZvD+v6TfOQRc1ixn+K4O/MZ6c6TcMkTT0UBbZzAaI5wm3W6RB6NkriRt6FpDhPFllPRiEk7lw2nEN9pZ6qqz8sTnkLq9a0pw=
  app:
    develop: mozillafestival-org-staging
    master: mozillafestival-org-production
