language: node_js
node_js:
  - '0.12'
deploy:
  provider: heroku
  api_key:
    secure: RCUYAeETpI/75exmUf5OzRJlSgw4uZI5Gjz/8mmwiKWTi8Dwile/KLSPD5xxvhY1ValJW2svQDJX+7pke+6ExbRBuObDOyymDel1k9sKCUwPn7HJP99s4z7oSePsBjCMHmkL7O0EyEHaOW55zBrie1O7Bu0G4UaA3+BBJVhcs9E=
  app:
    develop: mozillafestival-org-staging
    master: mozillafestival-org-production
